name: showhub
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  hexcolor: ^3.0.1
  flutter_screenutil: ^5.9.0

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Networking
  dio: ^4.0.6

  # Storage & Preferences
  shared_preferences: ^2.0.15

  # Utilities
  device_preview: ^1.1.0
  loader_overlay: ^4.0.1
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.2.4
  url_launcher: ^6.3.1

  # Media Players
  better_player: ^0.0.83
  video_player: ^2.8.1 # Added missing version number

  # Loading Animations
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # App Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/showhub.png"

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Custom Fonts
  fonts:
    - family: Poly
      fonts:
        - asset: assets/fonts/Poly-Regular.ttf
          weight: 500

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 600
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 500
        - asset: assets/fonts/Inter-Light.ttf
          weight: 400
